"""
iCal Bot - Automated Email to Calendar Invite System

This bot monitors your email inbox, uses a local LLM to detect event descriptions,
and automatically creates and sends calendar invites as email replies.
"""

import time
import json
import logging
from pathlib import Path
from typing import Set, Optional, Dict, Any, List

import config
from email_client import EmailClient
from exchange_client import ExchangeClient
from llm_client import LLMClient
from calendar_generator import CalendarGenerator
from storage import StorageManager
from messaging import build_reply_message

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class iCalBot:
    def __init__(self):
        # Choose email client based on protocol
        if config.EMAIL_PROTOCOL == "EXCHANGE":
            logger.info("Using Exchange Web Services (EWS)")
            self.email_client = ExchangeClient()
        else:
            logger.info("Using IMAP/SMTP")
            self.email_client = EmailClient()
            
        self.llm_client = LLMClient()
        self.calendar_generator = CalendarGenerator()
        self.processed_emails_file = Path(config.PROCESSED_EMAILS_FILE)
        self.processed_emails = self._load_processed_emails()
        self.storage = StorageManager(config.RESULTS_DB_PATH)
        self.processed_emails.update(self.storage.get_archived_email_ids())
        self.auto_approve_events = config.AUTO_APPROVE_EVENTS

        try:
            self.storage.censor_sensitive_fields()
        except Exception as exc:
            logger.warning("Startup censor failed: %s", exc)
        try:
            self.storage.purge_old_entries(days=30)
        except Exception as exc:
            logger.warning("Startup purge failed: %s", exc)

    @staticmethod
    def _is_autogenerated_reply(body: str) -> bool:
        if not body:
            return False
        normalized = body.lower()
        markers = [
            "generated automatically by ical bot",
            "i prepared a calendar invite based on your email",
            "— ical bot",
            "- ical bot",
            "this event was generated automatically by ical bot",
        ]
        return any(marker in normalized for marker in markers)
        
    def _load_processed_emails(self) -> Set[str]:
        """Load the set of already processed email IDs"""
        if self.processed_emails_file.exists():
            try:
                with open(self.processed_emails_file, 'r') as f:
                    data = json.load(f)
                    return set(data.get('processed_ids', []))
            except Exception as e:
                logger.error(f"Error loading processed emails: {e}")
                return set()
        return set()
    
    def _save_processed_emails(self):
        """Save the set of processed email IDs"""
        try:
            with open(self.processed_emails_file, 'w') as f:
                json.dump({'processed_ids': list(self.processed_emails)}, f)
        except Exception as e:
            logger.error(f"Error saving processed emails: {e}")
    
    def _record_processing_result(
        self,
        email_data: dict,
        *,
        has_event: bool,
        event_data: Optional[dict] = None,
        event_candidates: Optional[List[dict]] = None,
        selected_event_index: Optional[int] = None,
        ics_content: Optional[str] = None,
        status: str,
        error: Optional[str] = None,
        llm_metadata: Optional[Dict[str, Any]] = None,
        approval_required: bool = False,
        approval_status: Optional[str] = None,
        sent: Optional[bool] = None,
    ) -> None:
        """Persist processing outcome in the storage layer."""
        if not hasattr(self, 'storage'):
            return

        email_id = email_data.get('id')
        if not email_id:
            logger.warning("Cannot persist processing result without email ID")
            return

        preview = None
        if ics_content:
            preview = ics_content[:500] + '...' if len(ics_content) > 500 else ics_content

        send_flag = sent if sent is not None else (has_event and not config.DRY_RUN)
        llm_meta = llm_metadata or {}
        sanitized_raw_result = self._sanitize_llm_payload(llm_meta.get('raw_result'))
        prompt_injection = bool(llm_meta.get('prompt_injection'))

        try:
            self.storage.record_result(
                email_id=email_id,
                email_subject=email_data.get('subject', 'unknown'),
                email_sender=email_data.get('sender'),
                email_recipients=email_data.get('recipients'),
                email_date=email_data.get('date'),
                email_message_id=email_data.get('message_id'),
                has_event=has_event,
                event_data=event_data if has_event else None,
                event_candidates=event_candidates if has_event else None,
                selected_event_index=selected_event_index if has_event else None,
                ics_preview=preview,
                ics_content=ics_content,
                sent=send_flag,
                dry_run=config.DRY_RUN,
                status=status,
                error=error,
                llm_prompt=llm_meta.get('prompt'),
                llm_response=llm_meta.get('response_text'),
                llm_raw_result=sanitized_raw_result,
                prompt_injection=prompt_injection,
                approval_required=approval_required,
                approval_status=approval_status,
            )
            if approval_required and approval_status == "pending":
                self.storage.log_approval_action(email_id, "pending")
        except Exception as exc:
            logger.error(f"Failed to persist processing result: {exc}")

    @staticmethod
    def _sanitize_llm_payload(raw_result: Optional[Any]) -> Optional[Any]:
        """Remove heavyweight context arrays before persisting."""
        if raw_result is None:
            return None
        if isinstance(raw_result, str):
            try:
                parsed = json.loads(raw_result)
            except json.JSONDecodeError:
                return raw_result
            return iCalBot._sanitize_llm_payload(parsed)
        if isinstance(raw_result, dict):
            cleaned = {}
            for key, value in raw_result.items():
                if key == 'context':
                    continue
                cleaned[key] = value
            return cleaned
        return raw_result
    
    def process_email(self, email_data: dict) -> bool:
        """
        Process a single email: analyze for events and send calendar invite if needed
        
        Args:
            email_data: Dictionary containing email information
            
        Returns:
            True if calendar invite was sent, False otherwise
        """
        logger.info(f"Processing email: {email_data['subject']}")
        llm_metadata: Dict[str, Any] = {}

        try:
            if self._is_autogenerated_reply(email_data.get('body') or ''):
                logger.info("Detected auto-generated reply content; skipping")
                self._record_processing_result(
                    email_data,
                    has_event=False,
                    status="auto_reply_skipped",
                    llm_metadata=llm_metadata,
                )
                return False
            # Analyze email with LLM
            event_data, llm_metadata = self.llm_client.analyze_email_for_event(
                email_data['body'],
                email_data['subject'],
                reference_timestamp=email_data.get('date'),
            )
            
            # If no event detected, persist and skip
            if not event_data or not event_data.get('has_event'):
                logger.info("No event detected, skipping")
                self._record_processing_result(
                    email_data,
                    has_event=False,
                    status="no_event_detected",
                    llm_metadata=llm_metadata,
                )
                return False

            event_candidates = [
                candidate for candidate in (event_data.get('events') or []) if isinstance(candidate, dict)
            ]
            if not event_candidates and event_data.get('start_datetime'):
                event_candidates = [{
                    'title': event_data.get('title') or 'Untitled event',
                    'description': event_data.get('description') or '',
                    'start_datetime': event_data.get('start_datetime') or '',
                    'end_datetime': event_data.get('end_datetime') or '',
                    'location': event_data.get('location') or '',
                }]

            if not event_candidates:
                logger.info("LLM reported has_event=true but produced no usable candidates")
                self._record_processing_result(
                    email_data,
                    has_event=False,
                    status="no_event_detected",
                    llm_metadata=llm_metadata,
                )
                return False

            valid_candidates: List[dict] = []
            for candidate in event_candidates:
                if self.calendar_generator.validate_event_data(candidate):
                    valid_candidates.append(candidate)

            if not valid_candidates:
                logger.error("No valid future event candidates after validation")
                self._record_processing_result(
                    email_data,
                    has_event=False,
                    status="invalid_event_data",
                    llm_metadata=llm_metadata,
                )
                return False

            primary_event = valid_candidates[0]
            requires_selection = len(valid_candidates) > 1
            if requires_selection:
                logger.info("Multiple event candidates detected (%s); manual selection required", len(valid_candidates))
            
            recipients = list(email_data.get('recipients') or [])
            if not recipients and email_data.get('sender'):
                recipients = [email_data['sender']]

            # Always include the bot mailbox so the organizer gets the meeting request
            self_address = getattr(config, 'EMAIL_ADDRESS', None)
            if self_address and self_address not in recipients:
                recipients.append(self_address)
            email_data['recipients'] = recipients

            # Create iCalendar invite with attendee list
            ics_content = self.calendar_generator.create_ics_invite(
                primary_event,
                recipients=recipients,
            )
            reply_message = build_reply_message(primary_event, recipients)

            if config.DRY_RUN:
                logger.info("Dry run enabled; storing preview only")
                self._record_processing_result(
                    email_data,
                    has_event=True,
                    event_data=primary_event,
                    event_candidates=valid_candidates,
                    selected_event_index=0,
                    ics_content=ics_content,
                    status="dry_run_preview",
                    llm_metadata=llm_metadata,
                    approval_required=(not self.auto_approve_events) or requires_selection,
                    approval_status="dry_run",
                    sent=False,
                )
                return False

            if requires_selection:
                logger.info("Event candidates require manual selection before sending")
                self._record_processing_result(
                    email_data,
                    has_event=True,
                    event_data=primary_event,
                    event_candidates=valid_candidates,
                    selected_event_index=0,
                    ics_content=ics_content,
                    status="pending_approval",
                    llm_metadata=llm_metadata,
                    approval_required=True,
                    approval_status="pending",
                    sent=False,
                )
                return False

            if not self.auto_approve_events:
                logger.info("Event requires manual approval before sending")
                self._record_processing_result(
                    email_data,
                    has_event=True,
                    event_data=primary_event,
                    event_candidates=valid_candidates,
                    selected_event_index=0,
                    ics_content=ics_content,
                    status="pending_approval",
                    llm_metadata=llm_metadata,
                    approval_required=True,
                    approval_status="pending",
                    sent=False,
                )
                return False

            try:
                self.email_client.send_reply_with_calendar(
                    email_data,
                    ics_content,
                    reply_message,
                    dry_run=False
                )
            except Exception as exc:
                logger.error(f"Failed to send calendar invite: {exc}")
                self._record_processing_result(
                    email_data,
                    has_event=True,
                    event_data=primary_event,
                    event_candidates=valid_candidates,
                    selected_event_index=0,
                    ics_content=ics_content,
                    status="send_error",
                    error=str(exc),
                    llm_metadata=llm_metadata,
                    sent=False,
                )
                return False

            self._record_processing_result(
                email_data,
                has_event=True,
                event_data=primary_event,
                event_candidates=valid_candidates,
                selected_event_index=0,
                ics_content=ics_content,
                status="invite_sent",
                llm_metadata=llm_metadata,
                sent=True,
            )

            logger.info(f"✓ Calendar invite sent for: {primary_event['title']}")
            return True
            
        except Exception as e:
            logger.error(f"Error processing email: {e}")
            self._record_processing_result(
                email_data,
                has_event=False,
                status="processing_error",
                error=str(e),
                llm_metadata=llm_metadata,
            )
            return False
    
    def run_once(self):
        """Run a single check of the inbox"""
        logger.info("=" * 50)
        logger.info("Starting email check...")
        dry_run_target = config.DRY_RUN_TARGET_EVENTS if config.DRY_RUN else 0
        events_found = 0
        include_processed = config.DRY_RUN and dry_run_target > 0
        offset = 0
        run_seen_ids = set()
        
        try:
            while True:
                emails, has_more = self.email_client.fetch_unprocessed_emails(
                    self.processed_emails,
                    config.MAX_EMAILS_PER_CHECK,
                    offset=offset,
                    skip_processed=not include_processed,
                    exclude_ids=run_seen_ids
                )

                logger.info(
                    "Batch %s: fetched %s email(s)%s",
                    offset + 1,
                    len(emails),
                    " (including previously processed)" if include_processed else ""
                )

                if not emails and not has_more:
                    break

                if not emails and has_more:
                    offset += 1
                    continue
                
                for email_data in emails:
                    run_seen_ids.add(email_data['id'])
                    invite_sent = self.process_email(email_data)
                    self.processed_emails.add(email_data['id'])

                    if invite_sent:
                        events_found += 1
                        if include_processed and events_found >= dry_run_target:
                            logger.info(
                                "Reached dry-run event target (%s). Stopping early.",
                                dry_run_target
                            )
                            break

                    time.sleep(1)

                self._save_processed_emails()

                if include_processed and events_found >= dry_run_target:
                    break

                if not has_more:
                    break

                offset += 1

            if include_processed and events_found < dry_run_target:
                logger.info(
                    "Dry-run target (%s) not met; reached oldest available email.",
                    dry_run_target
                )

            logger.info("Email check completed")
        
        except Exception as e:
            logger.error(f"Error during email check: {e}")
    
    def run_continuous(self):
        """Run continuously, checking emails at regular intervals"""
        logger.info("iCal Bot started in continuous mode")
        logger.info(f"Checking emails every {config.CHECK_INTERVAL_SECONDS} seconds")
        logger.info("Press Ctrl+C to stop")
        
        try:
            while True:
                self.run_once()
                logger.info(f"Waiting {config.CHECK_INTERVAL_SECONDS} seconds until next check...")
                time.sleep(config.CHECK_INTERVAL_SECONDS)
                
        except KeyboardInterrupt:
            logger.info("\nStopping iCal Bot...")
            self._save_processed_emails()
            logger.info("Bot stopped")


def main():
    """Main entry point"""
    import sys
    
    bot = iCalBot()
    
    # Check command line arguments
    if len(sys.argv) > 1 and sys.argv[1] == '--once':
        # Run once and exit
        bot.run_once()
    else:
        # Run continuously
        bot.run_continuous()


if __name__ == "__main__":
    main()
